
version: '3.9'
services:

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: manageYourCompany-mongodb-container
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - manageYourCompany-mongodb-data:/data/db

  # Backend service
  vacation-backend-service:
    image: oz1987/manageYourCompany-backend-image:1.0
    build: ./backend
    container_name: manageYourCompany-backend-container
    ports:
      - 4000:4000
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGODB_HOST=mongodb
      - MONGODB_DATABASE=manageYourCompany
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  # Frontend service
  vacation-frontend-service:
    image: oz1987/manageYourCompany-frontend-image:1.0
    build: ./frontend
    container_name: manageYourCompany-frontend-container
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    depends_on:
      - manageYourCompany-backend-service

volumes:
  vacation-mongodb-data:


# ===================================== terminal commands ==========================

# run docker compose -> using terminal:
# docker-compose up                (run docker)
# docker-compose up -d             (run docker and detach terminal)
# docker-compose up -d --build     (same and build image if even exist)
# docker-compose down              (stop and delete container)